### ISSUE TITLE
`-s, --skipProgressBar` option

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/takajo#121]
It would be nice to have a `-s, --skipProgressBar` option for all commands that display the progress bar for when takajo is being used in a batch script, etc... and it does not matter to check the progress. This is to speed thing up a bit by not counting the lines in order to display the progress bar.

**Comment by fukusuket** [comment]
In addition to implementing #132, it seems that skipProgressbar will also be necessary, so I will try implementing it💪
