### ISSUE TITLE
`stack-computers` command

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/takajo#125]
Similar to the `computer-metrics` command in hayabusa, it will stack unique entries of the `.Computer` field.
I would like to output in the table format for standard output and CSV file output and add `Levels` and `Alerts` similar to takajo's `stack-services` command. It would be nice to print how many alerts for each level and alert.
Example:

| Count | Computer  | Levels                              | Alerts                                                                                  |
|-------|-----------|-------------------------------------|-----------------------------------------------------------------------------------------|
| 500   | ComputerA | crit (10) \| high (20) \| info (xx) | CobaltStrike Service Installations - System (10) \| Alert2 (20) \| Alert3 (5) \| etc... |
| 100   | ComputerB | high (10) \| low (10) \| info (100) | Drive-by Compromise (10) \| etc...                                                      |
| 1     | ComputerC | hogehoge                            | hogehoge                                                                                |

The difference between `stack-computers` and `computer-metrics` is that `stack-computers` only gets info from Hayabusa results but Hayabusa's `computer-metrics` will take metrics on all events regardless of sigma rules.

We should probably add this option:
`-m=, --minLevel=  specify the minimum alert level (default: informational)`

@fukusuket Are you interested in this?

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you so much :) Yes, I would love to implement it💪
