### ISSUE TITLE
Support `-d, --directory`

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/takajo#133]
Support `-d, --directory` to load multiple JSONL files. For example, when multiple JSONL files are returned from Velociraptor.

**Comment by hitenkoku** [comment]
@YamatoSecurity I am aware that the timeline option specifies a single file and the directory option cannot be used with the timeline option.

If I make the timeline opution in CLIGEN, I will not be able to get the REQUIRED help I have been getting so far, is that a problem?

If that is the case, I think it would be better to make the timeline option directory-compatible, what do you think?

**Comment by YamatoSecurity** [comment]
@hitenkoku That is a good idea! Yes, let's make `--timeline` compatible with directories so that if a directory is specified it will recursively scan for `*.jsonl` files to load.
