### ISSUE TITLE
Takajo does not support other time formats

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/takajo#141]
When I use `--ISO-8601` time format in Hayabusa, I get the following error when running `automagic`:

```
times.nim(1644)          raiseParseException
Error: unhandled exception: Failed to parse '2018-05-03T19:29:27.' with format 'yyyy-MM-dd HH:mm:ss'.'fff'. Unexpected character: T [TimeParseError]
```

@fukusuket Is it possible to auto-detect the timestamp format and support all of the time formats that Hayabusa does?

**Comment by fukusuket** [comment]
@YamatoSecurity 
When I commented out `timeline-logon` with the automagic command, it was successful with `--ISO-8601`, so the following parsing process seems to be the cause🤔 (I don't think there is any other process to parse the timestamp.)
- https://github.com/Yamato-Security/takajo/blob/main/src/takajopkg/timelineLogon.nim#L187-L188

It should be possible to solve the problem by just making the above corrections, so I will try to fix it💪
