### ISSUE TITLE
Add failed logon summary to `stack-logons`

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/takajo#152]
Hayabusa's `logon-summary` currently cannot remove duplicate entries so to work around this, users can remove duplicates with the `json-timline` command and then use Takajo's `stack-logons` command to get the same information. However, `stack-logons` cannot currently list up failed logons. I would like to add a `-f, --failedLogons   stack failed logons instead of successful logons (true/false)` option to `stack-logons` that has the same behavior as the Failed Logons output in Hayabusa's `logon-summary` command.

@fukusuket Since you are most knowledgable about this, can I ask you to do add this?

I would also like to output the failed logon summary with `automagic`

**Comment by fukusuket** [comment]
Yes, I would love to implement it!💪
