### ISSUE TITLE
Allow filtering on the Chart by Rules

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/takajo#177]
Under the `Detection Rule List` in the Computer Summary, it would be nice to be able to filter on rules. 

<img width="1283" alt="Screenshot 2024-08-30 at 09 26 22" src="https://github.com/user-attachments/assets/70fb7675-dec2-44c9-89ac-48a2300db8a8">

So between `Detection Rule List` and the `ALERT TITLE` table, I want to add 2 links:
```
Include all rules
Exclude all rules
```

`Include all rules` will mark of the rules checked. `Exclude all rules` will uncheck all rules and make the table blank.

To the left of `ALERT TITLE`, I want to add another column called `INCLUDE?` which will contain checkboxes (if possible)

The user can then check or uncheck the rules which will update the chart above.

@nishikawaakira Is this possible to do with static pages? or will we need the dynamic web server for this?

**Comment by nishikawaakira** [comment]
It seems difficult to implement this in static HTML, since it is displayed in aggregate on the server side, and I would like to support this when implementing a dynamic web server.
