### ISSUE TITLE
New Feature: Logon Timeline

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/takajo#20]
WELAのログオンタイムライン機能と同じようなログオンタイムライン作成。
https://github.com/Yamato-Security/WELA/blob/main/Screenshots/Screenshot-LogonTimelineGUI.png

出力するフィールド:
`Target Computer (%Computer%フィールド), Logon Time, Logoff Time, Elapsed Time, Type, Auth, Target User, Admin, Source Computer, Source IP Address, Process Name`

標準出力の場合はHayabusaのようにフィールドを`‖`の区切りで分ける。
`-o`のファイル保存はCSV。

**Comment by hitenkoku** [comment]
関連するルールをリストアップしてみました。このルールの検知結果(csv)をtakajoのinputとすることでよろしいでしょうか。
なお、各種detailsだとデータが足りない可能性が高いのでsuper-verboseでデータをとってもらってデータを集計したほうが良いと思いますがいかがでしょうか。

- WELAでの集計(EIDをもとに集計）
  - Logon
    - 4624
    - 4776
    - 21 (ProviderName: Microsoft-Windows-TerminalServices-LocalSessionManager)
    - 25 (ProviderName: Microsoft-Windows-TerminalServices-LocalSessionManager)
  - Logoff
    - 4634
    - 4647

- 対応すると思われるHayabusa-rule
  - Logon
    - 4624 
      - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-0-System.yml
      - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-2-Interactive.yml
      - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-3-Network.yml
      - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-4-Batch.yml
      - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-5-Service.yml
      - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-7-Unlock.yml
      - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-8-NetworkCleartext.yml
      - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-9-NewInteractive.yml
      - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-10-RemoteInteractive.yml
      - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-11-CachedInteractive.yml
      - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-12-CachedRemoteInteractive.yml
       - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/LogonLogoff/Logon/Sec_4624_Info_Logon-Type-13-CachedUnlock.yml
  - 4776
    - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/AccountLogon/CredentialValidation/Sec_4776_Info_NTLM-Auth.yml
  - 21 (ProviderName: Microsoft-Windows-TerminalServices-LocalSessionManager)
    - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/TerminalServices-LocalSessionManager_Op/LocalSessManager_21_Info_RDS-SessLogon.yml
  - 25 (ProviderName: Microsoft-Windows-TerminalServices-LocalSessionManager)
    - Not found
- Logoff
  - 4634
    - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/LogonLogoff/Logoff/Sec_4634_Info_Logoff.yml
  - 4647
    - https://github.com/Yamato-Security/hayabusa-rules/blob/main/hayabusa/builtin/Security/LogonLogoff/Logoff/Sec_4647_Info_LogoffUsrInitiated.yml

**Comment by YamatoSecurity** [comment]
@hitenkoku コメントありがとうございます！一旦二人で話した方が良さそうなので、再来週辺り時間がある時に今考えていること、課題等をリストアップして、話し合いましょうか？

**Comment by hitenkoku** [comment]
memo: 投入された時刻が度のフォーマットかを処理する必要あり。オプションを絞るかそれかNim側でチェックをするか

**Comment by YamatoSecurity** [comment]
プロトタイプは一旦こちらで作ってみます！

**Comment by hitenkoku** [comment]
コメントありがとうございます。承りました。一旦私のassignをはずさせていただきました。

**Comment by YamatoSecurity** [comment]
closed with version 2.0.0
