### ISSUE TITLE
Rename package zip filenames

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/takajo#203]
@fukusuket 
Whenever you get time, could you update the Takajo automation to be more similar to Hayabusa's?
That is, include a `all-packages.zip` file that has all the packages and documents zip?

Also, I want to rename `takajo-2.7.0-linux-intel.zip` to `takajo-2.7.0-lin-x64-gnu.zip`, `takajo-2.7.0-mac-arm.zip` to `takajo-2.7.0-mac-aarch64.zip`, `takajo-2.7.0-mac-intel.zip` to `takajo-2.7.0-mac-x64.zip`

**Comment by fukusuket** [comment]
I forgot to rename the takajo packages names... I will fix it!
