### ISSUE TITLE
New Feature Suggest: Process tree output

### ISSUE THREAD

**Issue by hitenkoku** [Yamato-Security/takajo#24]
image(msiticpy): 
  https://github.com/microsoft/msticpy/blob/main/docs/source/visualization/_static/process_tree3.png
  
  プロセスツリーを出力する機能の実装
  標準出力で出力するような形でまず実装する。

プロセスツリーの出力はHayabusaのsuper-verboseやSysmonのProcess create等をもとに作成する

**Comment by YamatoSecurity** [comment]
お疲れ様です！早速ですが、落ち着いたタイミングで良いので、これをお願いできますか？
今https://github.com/Yamato-Security/takajo/tree/2.0.0-dev で2.0.0を開発しているので、そちらをcheckoutして使って下さい。sysmonProcessTree.nimで途中まで作ってみたのですが、よく分からないのでお願いできたら大変助かります。
m(__)m

イメージ: ユーザがHayabusaのsysmonアラートでマルウェアのプロセスを特定できて、そのプロセスの親子関係を調べたい時のコマンドです。
取り敢えず、Timestamp, PID (PGUID), Parent PID (Parent PGUID)を入れたいです。

例: -p 365ABB72-47BB-5CE3-0000-00108CAD3E00 すると


```
rootproc.exe (2019-05-21 09:35:07.308 +09:00 / 3176 / 365ABB72-47BB-5CE3-0000-0010BFA83E00 )
  |- prog1.exe (2019-05-22 02:32:00.482 +09:00 / <PID> / <PGUID> )
  |- prog2.exe (2019-05-23 02:32:00.482 +09:00 <PID> / <PGUID> )
  |   |- prog3.exe (2019-05-23 01:32:00.482 +09:00 <PID> / <PGUID> )
  |- malware.exe (2019-05-22 02:32:00.482 +09:00 / 9343 / 365ABB72-47BB-5CE3-0000-00108CAD3E00 )
```

が表示されます。親プロセスが起動した他の個プロセスも出力したいです。

https://github.com/Yamato-Security/takajo/tree/2.0.0-dev の`src/takajopkg/sysmonProcessTree.nim`があるので、その修正をお願いします。

**Comment by hitenkoku** [comment]
@YamatoSecurity  ひとまず、現在の2.0.0-devをmergeしてみました。現在内容については確認中ですが、不明点があるため確認させてください。

- 提示いただいたプロセスツリーが表示されない
  例で提示していただいたような表示に現在なっていないため、どのようなデータセットで行ったかの情報をいただけますでしょうか。現在私が確認したデータは以下の通りです。
   ```
./hayabusa.exe json-timeline -d ..\hayabusa-sample-evtx\ -o hse-260-sysmon-1.jsonl -L -p standard -C -r .\rules\hayabusa\sysmon\Sysmon_1_Info_ProcExec.yml 
   ```
   
   実行した結果が以下の通りです。outputで指定したファイルは作成されていませんでした。
   
   ````
> ./takajo.exe sysmon-process-tree -t .\hse-260-sysmon-1.jsonl -o ./result.txt -p 365ABB72-47BB-5CE3-0000-00108CAD3E00 -q

Running the Process Tree module

Process 365ABB72-47BB-5CE3-0000-00108CAD3E00
> 
   ````

**Comment by YamatoSecurity** [comment]
@hitenkoku 
確認ありがとうございます。
`./hayabusa.exe json-timeline -d ..\hayabusa-sample-evtx\ -o test.jsonl -L`でサンプルデータを作りました。

現在は、開発が途中でgive upしてしまったので、`Process 365ABB72-47BB-5CE3-0000-00108CAD3E00`などしか出力されません。
```
type
    processObject = ref object
        processGUID: string
        parentProcessGUID: string
        children: seq[processObject]

proc printIndentedProcessTree(p: processObject, indent: string = "") =
  echo(indent & "Process ", p.processGUID)
  for child in p.children:
    printIndentedProcessTree(child, indent & "  ")
```
等々のコードは適当に入れたので、自由に削除したり、修正したりして下さい。
`Process 365ABB72-47BB-5CE3-0000-00108CAD3E00`の代わりに
```
rootproc.exe (2019-05-21 09:35:07.308 +09:00 / 3176 / 365ABB72-47BB-5CE3-0000-0010BFA83E00 )
  |- prog1.exe (2019-05-22 02:32:00.482 +09:00 / <PID> / <PGUID> )
  |- prog2.exe (2019-05-23 02:32:00.482 +09:00 <PID> / <PGUID> )
  |   |- prog3.exe (2019-05-23 01:32:00.482 +09:00 <PID> / <PGUID> )
  |- malware.exe (2019-05-22 02:32:00.482 +09:00 / 9343 / 365ABB72-47BB-5CE3-0000-00108CAD3E00 )
```
のプロセスツリーを出力したいです。
`-o`のファイル保存もまだできていない状態です。標準出力ができてから、入れようと思っていました。

**Comment by hitenkoku** [comment]
@YamatoSecurity ご回答ありがとうございます。ご提示いただいた例のような出力になるようにすれば良いとのことですね。それでは対応いたします

**Comment by hitenkoku** [comment]
@YamatoSecurity  作成が完了しました。お時間があるときにご確認のほどよろしくお願いいたします。
https://github.com/Yamato-Security/takajo/pull/26

**Comment by YamatoSecurity** [comment]
@hitenkoku ありがとうございます！
`)`の前に改行が入っていたので、改行が出力しないように少し修正しました。
また、`info`レベルのプロセス作成ルールしか見ていなかったけど、`high`レベルも見る必要があるので、ruleTitleを見るように修正しました。

以下の確認＋修正をお願いできますか？
1. `./takajo sysmon-process-tree -t ../hayabusa/samplejson.jsonl -p 747F3D96-B764-5EA4-0000-00106F550000`で検証した時に
```
  │  ├ C:\Windows\System32\sihost.exe (2020-04-26 07:19:32.050 +09:00 / 747F3D96-B767-5EA4-0000-0010FE2E0200 / 747F3D96-B765-5EA4-0000-0010DCDF0000)
  │  ├ C:\Windows\System32\sihost.exe (2020-04-26 07:19:32.050 +09:00 / 747F3D96-B767-5EA4-0000-0010FE2E0200 / 747F3D96-B765-5EA4-0000-0010DCDF0000)
  │  ├ C:\Windows\System32\sihost.exe (2020-04-26 07:19:32.050 +09:00 / 747F3D96-B767-5EA4-0000-0010FE2E0200 / 747F3D96-B765-5EA4-0000-0010DCDF0000)
  │  ├ C:\Windows\System32\sihost.exe (2020-04-26 07:19:32.050 +09:00 / 747F3D96-B767-5EA4-0000-0010FE2E0200 / 747F3D96-B765-5EA4-0000-0010DCDF0000)
  │  ├ C:\Windows\System32\sihost.exe (2020-04-26 07:19:32.050 +09:00 / 747F3D96-B767-5EA4-0000-0010FE2E0200 / 747F3D96-B765-5EA4-0000-0010DCDF0000)
  │  ├ C:\Windows\System32\sihost.exe (2020-04-26 07:19:32.050 +09:00 / 747F3D96-B767-5EA4-0000-0010FE2E0200 / 747F3D96-B765-5EA4-0000-0010DCDF0000)
  │  ├ C:\Windows\System32\sihost.exe (2020-04-26 07:19:32.050 +09:00 / 747F3D96-B767-5EA4-0000-0010FE2E0200 / 747F3D96-B765-5EA4-0000-0010DCDF0000)
  │  ├ C:\Windows\System32\sihost.exe (2020-04-26 07:19:32.050 +09:00 / 747F3D96-B767-5EA4-0000-0010FE2E0200 / 747F3D96-B765-5EA4-0000-0010DCDF0000)
  │  ├ C:\Windows\System32\sihost.exe (2020-04-26 07:19:32.050 +09:00 / 747F3D96-B767-5EA4-0000-0010FE2E0200 / 747F3D96-B765-5EA4-0000-0010DCDF0000)
  │  ├ C:\Windows\System32\sihost.exe (2020-04-26 07:19:32.050 +09:00 / 747F3D96-B767-5EA4-0000-0010FE2E0200 / 747F3D96-B765-5EA4-0000-0010DCDF0000)
  │  ├ C:\Windows\System32\sihost.exe (2020-04-26 07:19:32.050 +09:00 / 747F3D96-B767-5EA4-0000-0010FE2E0200 / 747F3D96-B765-5EA4-0000-0010DCDF0000)
  │  └ C:\Windows\System32\sihost.exe (2020-04-26 07:19:32.050 +09:00 / 747F3D96-B767-5EA4-0000-0010FE2E0200 / 747F3D96-B765-5EA4-0000-0010DCDF0000)
```
のようにプロセス情報が何回も出力されています。タイムスタンプとProcessGUIDが一致している場合は一回だけ出力したいです。
親プロセスのsvchost.exeも何回も出力されています。

2. 現在、タイムスタンプ / processGUID / parentProcessGUIDの情報を出力していますが、タイムスタンプ / processID / processGUIDの３つの情報を出力するようにお願いできますか？
3. `./takajo sysmon-process-tree -t ../hayabusa/samplejson.jsonl -p A57649D1-3BC7-6189-091B-5D0300000000`を実行するとプロセスツリーが出力されなくて、`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe (2021-11-09 00:01:27.604 +09:00 / A57649D1-3BC7-6189-091B-5D0300000000 / A57649D1-1303-6179-D9C8-010000000000)`しか出力されませんが、原因わかりますか？

**Comment by YamatoSecurity** [comment]
closed with version 2.0.0
