### ISSUE TITLE
Make VT requests multithreaded

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/takajo#30]
I would like to make the VT requests (vt-domain-lookup, vt-hash-lookup, vt-ip-lookup commands) multithreaded to make VT lookups much faster.
Also, I would like to use [Puppy](https://github.com/treeform/puppy) for HTTPS requests if possible as it does not require including extra DLLs, etc... However, we need to test that it works on Win, mac and linux first.

@fukusuket Are you interested in this?

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you for the mention :) Yes, I would love to implement it!💪 I would like to start by studying Nim programming ^^

**Comment by YamatoSecurity** [comment]
@fukusuket Oh great, thanks!

**Comment by fukusuket** [comment]
@YamatoSecurity 
I have a question!  What's the main reason you want to use Puppy if we can? 
(Does it have anything to do with parallelization?)

**Comment by fukusuket** [comment]
Puppy's compile error(with Nim 2.0.0) was fixed by merging the following PR ^^
- https://github.com/treeform/puppy/pull/107
