### ISSUE TITLE
[bug] `timeline-suspicious-process` command failed `Error: unhandled exception: invalid hex integer:  [ValueError]` 

### ISSUE THREAD

**Issue by fukusuket** [Yamato-Security/takajo#35]
**Describe the bug**
`timeline-suspicious-process` failed due to  `Error: unhandled exception: invalid hex integer:  [ValueError]` 

**Step to Reproduce**
1. `./hayabusa-2.8.0-mac-arm json-timeline -d hayabusa-sample-evtx -L -o result.jsonl`
2. `./takajo-2.0.0-mac-arm timeline-suspicious-process -t result.jsonl`

**Expected behavior**
Error does not occur

**Actual behavior**
Following error occur.
```
fukusuke@fukusukenoMacBook-Air hayabusa-2.8.0-all-platforms % ./takajo-2.0.0-mac-arm timeline-suspicious-process -t result.jsonl
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║╔╗╔╗║╔═╗║║║╔╣╔═╗║ ║║╔═╗║
╚╝║║╚╣║ ║║╚╝╝║║ ║║ ║║║ ║║
  ║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
 ╔╝╚╗║╔═╗║║║╚╣╔═╗║╚╝║╚═╝║
 ╚══╝╚╝ ╚╩╝╚═╩╝ ╚╩══╩═══╝
  by Yamato Security

Started the Timeline Suspicious Processes command

This command will a CSV timeline of suspicious processes.
The default minimum level of alerts is high.
You can change the minimum level with -l, --level=.

Counting total lines. Please wait.

Total lines: 32265

Scanning for processes with a minimal alert level of high

  0%|                         |     0/32265 [ 0.0s<  ??s,      ??/sec]strutils.nim(1046)       fromHex
Error: unhandled exception: invalid hex integer:  [ValueError]
```

**Environment**
 - OS: macOS 
 - Takajo version 2.0.0
 - Hayabusa version 2.8.0

**Additional context**
This issue would not have occurred if the PID had not been converted using the `-F` option.
`./hayabusa-2.8.0-mac-arm json-timeline -d hayabusa-sample-evtx -L -o result.jsonl -F`

Therefore, it was a problem that occurred when using the following functions released in Hayabusa 2.8.0.
https://github.com/Yamato-Security/hayabusa/pull/1154

**Comment by hjadot** [comment]
Hello, I had the same error today with the windows64 version, how can I fix this ?

![image](https://github.com/Yamato-Security/takajo/assets/32583242/3e1d37d7-c4e7-463a-9609-839a02fa0874)
![image](https://github.com/Yamato-Security/takajo/assets/32583242/f65b655f-91bf-4989-a9c5-730d83ec9a47)
Thanks for your help !

**Comment by fukusuket** [comment]
@hjadot 
Hello, Thank you for using tool :)  Is the Takajo version you are using 2.0.0?

This issue was fixed latest main, but not yet released.(The next version will be released soon)
I think the issue is resolved by building with the latest commit of main using the steps below, how is it?
1. [Install Nim 2.0.0](https://nim-lang.org/install_windows.html)
2. [Compile Takajo](https://github.com/Yamato-Security/takajo#git-cloning)

**Comment by hjadot** [comment]
Hello yes was using 2.0.0. I built from the latest commit and it is indeed working. Thanks for the fast reply !

![image](https://github.com/Yamato-Security/takajo/assets/32583242/b957eb3e-fea0-44e9-ad09-8431166f7b84)

**Comment by fukusuket** [comment]
@hjadot 
Thank you for comment. Yes, It's a typo! This will be fixed in the pull request below :)
https://github.com/Yamato-Security/takajo/pull/60
