### ISSUE TITLE
[bug] not working `-s` option in `list-domain` command

### ISSUE THREAD

**Issue by DYarizadeh** [Yamato-Security/takajo#37]
-s flag is not recognized when attempting to include subdomains 

Reports as "Unknown short option: "s""

**Comment by fukusuket** [comment]
@DYarizadeh 
Hello, I tested with the following command, but could not reproduce the same issue.
```
fukusuke@fukusukenoAir hayabusa-2.8.0-all-platforms % ./takajo-2.0.0-mac-arm list-domains -t result.jsonl -o domains.txt -s
╔════╦═══╦╗╔═╦═══╗ ╔╦═══╗
║╔╗╔╗║╔═╗║║║╔╣╔═╗║ ║║╔═╗║
╚╝║║╚╣║ ║║╚╝╝║║ ║║ ║║║ ║║
  ║║ ║╚═╝║╔╗╖║╚═╝╠╗║║║ ║║
 ╔╝╚╗║╔═╗║║║╚╣╔═╗║╚╝║╚═╝║
 ╚══╝╚╝ ╚╩╝╚═╩╝ ╚╩══╩═══╝
  by Yamato Security

Started the List Domains command

Local queries to workstations are filtered out by default, but can be included with -w, --includeWorkstations.
Sub-domains are also filtered out by default, but can be included with -s, --includeSubdomains.
Domains ending with .lan, .LAN or .local are filtered out.

Counting total lines. Please wait.

Total lines: 1627290

Extracting domain queries from Sysmon 22 events. Please wait.

100%|█████████████████████████| 1627291/1627290 [16.0s< 0.9s,  78.73k/sec]

Domains: 957
Saved file: domains.txt (22.06 KB)

Elapsed time: 0 hours, 0 minutes, 18 seconds
```
As stated in the README below, the `-s` option can only be used with the `list-domains` command, what command did you execute?
https://github.com/Yamato-Security/takajo#list-domains-command

**Comment by DYarizadeh** [comment]
Sorry, I misinterpreted the instructions. 

Hopefully in the future we can add a feature that will query subdomains using the vt-domain-lookup command as at the moment it looks like it will only return results for domains. Unless I'm doing that incorrectly as well :)

**Comment by fukusuket** [comment]
@DYarizadeh 
The current `vt-domain-lookup` command behavior is to search VirusTotal for each line of text specified with the `-d, --domainList` option.(In other words, if the text specified with `-d` includes a subdomain, it will also search for the subdomain.)

Therefore, I think you can achieve what you want by executing `list-domains` with the `-s` option and specifying the result text to the `vt-domain-lookup` command  `-d` option :)

**Comment by YamatoSecurity** [comment]
@DYarizadeh Thanks for the question. 
@fukusuket Thanks for the response! Yes, as @fukusuket mentioned, this is already possible as he described.

Is it alright if I close this issue if you  do not have any more questions/requests?

**Comment by YamatoSecurity** [comment]
No more further questions, so closing this.
