### ISSUE TITLE
Remove `ignoring duplicate libraries` warning

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/takajo#45]
When compiling, I get a `ld: warning: ignoring duplicate libraries: '-lm'` warning. @fukusuket Do you know how to get rid of this?

```
nimble build -d:release --threads:on
  Verifying dependencies for takajo@2.0.0
     Info:  Dependency on cligen@>= 1.5 already satisfied
  Verifying dependencies for cligen@1.6.13
     Info:  Dependency on suru@#f6f1e607c585b2bc2f71309996643f0555ff6349 already satisfied
  Verifying dependencies for suru@0.3.1
     Info:  Dependency on puppy@>= 2.1.0 already satisfied
  Verifying dependencies for puppy@2.1.0
     Info:  Dependency on libcurl@>= 1.0.0 already satisfied
  Verifying dependencies for libcurl@1.0.0
     Info:  Dependency on zippy@>= 0.10.0 already satisfied
  Verifying dependencies for zippy@0.10.10
     Info:  Dependency on webby@>= 0.1.6 already satisfied
  Verifying dependencies for webby@0.1.9
   Building takajo/takajo using c backend
ld: warning: ignoring duplicate libraries: '-lm'
```

**Comment by fukusuket** [comment]
@YamatoSecurity 
It seems to be caused by a recent Xcode update, but I'll investigate to see if there's a way to get rid of it!💪
- https://github.com/orgs/Homebrew/discussions/4794
- https://developer.apple.com/forums/thread/733317

**Comment by fukusuket** [comment]
There seems to be a possibility that this is a bug on the Xcode side, so I would like to wait for more new information!

**Comment by YamatoSecurity** [comment]
@fukusuket Thanks for investigating this. In that case, indeed let's wait for new information then.

**Comment by YamatoSecurity** [comment]
This is no longer being displayed with Nim 2.2.0
