### ISSUE TITLE
`sysmon-process-tree` command does not show root process

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/takajo#54]
`sysmon-process-tree` command does not show root processes like `explorer.exe` because those processes start up before sysmon and do not have a log that the process was launched. However, we can still get the parent process name and GUID from the parent process field information indirectly so I would like to output the parent root process as well.

Because we are outputting the child processes recursively, if we outputted all child processes from the root process it would be too much information, so in case of the root process, I don't want to output the other child processes.

If a user specifies a root process GUID, then recursively all child process information of that root process should be outputted.

@fukusuket Could I ask you to do this issue?

**Comment by fukusuket** [comment]
Thank you for the mention :) Yes, I would love to implement it!💪

**Comment by YamatoSecurity** [comment]
closed by https://github.com/Yamato-Security/takajo/pull/56
