### ISSUE TITLE
Parse and analyze partition diagnostic log

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/takajo#67]
Port over https://github.com/theAtropos4n6/Partition-4DiagnosticParser to a Hayabusa rule and Takajo command.
@fukusuket Would you be interested in this? I think we first need a hayabusa rule to extract out this log and then create a CSV timeline of when USB devices were connected.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you for mention:) Yes! I would love to implement it 💪 
I'd like to start by checking what kind of log it is.

**Comment by YamatoSecurity** [comment]
Great! no rush. Please check it out whenever you have time.
