### ISSUE TITLE
Deprecated usage of `spawn` in VT lookup commands

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/takajo#81]
After updating nim to 2.0.2 with `choosenim update stable` I am getting the following error:
```
takajo-main/src/takajo.nim(15, 8) Warning: use the nimble packages `malebolgia`, `taskpools` or `weave` instead; threadpool is deprecated [Deprecated]
```

**Comment by YamatoSecurity** [comment]
@fukusuket I found the cause of this. In the three `vt` commands, it is causing the deprecated error due to the use of `spawn` from the `threadpool` library. Could you rewrite the parallel processing to use `malebolgia` instead?
https://github.com/Araq/malebolgia
`malebolgia` is written by the author of Nim so will probably be maintained in the future and seems to be suitable for our purpose.

**Comment by fukusuket** [comment]
@YamatoSecurity 
Thank you for the information! Yes, I'll try it💪
