### ISSUE TITLE
[bug] timeline-suspicious-process output not writing file

### ISSUE THREAD

**Issue by TazWake** [Yamato-Security/takajo#86]
**Describe the bug**
I am trying to get `timeline-suspicious-process` to write the output to a CSV file. The command runs (and works perfectly displaying data to screen) but every time I provide a `-o` or `--output` argument it fails to write the file to disk.

**Step to Reproduce**
Steps to reproduce the behaviour:

1. Run `takajo timeline-suspicious-processes -t /cases/sysmon_evtx_timeline.jsonl -o /cases/testing/output.csv -q`
2. Run `ls /cases/testing` nothing is there.

**Expected behaviour**
A CSV file containing the timeline of suspicious processes.

**Screenshots**
![image](https://github.com/Yamato-Security/takajo/assets/26778008/6b807db2-fc4d-4584-8702-c1ab19305110)

**Environment (please complete the following information):**
 - OS: Tried on Ubunut 20.04 and Ubuntu 22.04
 - OS: Tried on Windows 10 and Windows 11
 - Takajo version 2.3.0

**Additional context**
It works really well when outputting data to the screen but, with 47849 records it isn't possible to review them and running data minimisation is hard at this stage.

I am not sure if I've missed a critical step but all the other commands appear to write output with no issues and I've tried this on three different VMs now.

**Comment by YamatoSecurity** [comment]
Hi @TazWake 
Thank you very much for the issue. It is indeed a bug and is happening due to my bad `if` logic here:
`if output != "" and suspicousProcessCount_Sec_4688 != 0 and suspicousProcessCount_Sysmon_1 != 0: # Save results to CSV`
Because you have zero Sec 4688 events, it is not saving the file. (Need to change the second `and` to an `or`). I will try to fix ASAP for you.

**Comment by TazWake** [comment]
Awesome - than you for such a quick and positive response! It is an awesome tool.

**Comment by YamatoSecurity** [comment]
Hi @TazWake 
Glad you like the tool! Sorry for the wait, I just uploaded the new release binaries that should fix this issue: https://github.com/Yamato-Security/takajo/releases/tag/v2.3.1

**Comment by TazWake** [comment]
Thank you so much for the super-fast response here. I truly appreciate the time and effort you have put into such an awesome tool.
