### ISSUE TITLE
Release build action uses deprecated actions

### ISSUE THREAD

**Issue by YamatoSecurity** [Yamato-Security/takajo#89]
The following warnings are displayed when running the release build action:

`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/upload-artifact@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`

**Comment by fukusuket** [comment]
The cause was that upload-artifact v3 was using old node-js. This will be resolved by updating to v4.
https://github.com/actions/upload-artifact
